services:
  nginx-dev:
    restart: unless-stopped
    stop_signal: SIGKILL
    depends_on: []
    networks: [net-food]
    ports:
      - "127.0.0.1:8443:80"
    volumes:
      - ./build/nginx/food-dev.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      dockerfile: ./build/dockerfiles/nginx-dev.Dockerfile

  # frontend-dev:
  #   restart: unless-stopped
  #   volumes:
  #     - ./frontend:/app
  #   env_file: [.env]
  #   networks: [net-food]
  #   user: "${UID}:${GID}"
  #   build:
  #     context: ./frontend
  #     dockerfile: ../build/dockerfiles/frontend-dev.Dockerfile

networks:
  net-food:
    driver: bridge
