[Migration]
Hash = "13863245877395763969"
Initial = false
Dependency = 1
Replaces = []

[[Migration.Operations]]
Type = "DeleteField"
Model = "recipesteps"
Name = "step"

[[Migration.Operations]]
Type = "CreateField"
Model = "recipesteps"

[Migration.Operations.Field]
Name = "step"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 256

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/recipe_steps.rs"
Line = 23
Column = 9

[[Migration.Operations]]
Type = "DeleteField"
Model = "recipe"
Name = "user"

[[Migration.Operations]]
Type = "CreateField"
Model = "recipe"

[Migration.Operations.Field]
Name = "user"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "user"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/recipe.rs"
Line = 25
Column = 9
